# Generated by Django 4.2.4 on 2023-08-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
