# Generated by Django 4.2.4 on 2023-08-27 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_link_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="views",
            new_name="viewcount",
        ),
        migrations.AddField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
